#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 186415-web-01 54.157.163.189:80 check\n\tserver 186415-web-02 100.26.238.224:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
